### ISSUE TITLE
Out of Memory - Google Colab

### ISSUE THREAD

**Issue by bradley-pearson6597** [pharmapsychotic/clip-interrogator#60]
I am running the CLIP interrogator in Google Colab. It was working fine yesterday but it seems like Pytorch is allocating a significant amount of memory?

```
CUDA out of memory. Tried to allocate 6.76 GiB (GPU 0; 14.75 GiB total capacity; 11.73 GiB already allocated; 1.93 GiB free; 11.78 GiB reserved in total by PyTorch)
```

Is there a solution for this/what is causing this?

**Comment by OneRasel** [comment]
> @WalidAliAlfaid and for anyone else having this issue. Installing these packages instead of those in the Colab fixed the issue for me:
> 
> ```python
> !pip install torch
> !pip install torchvision
> !pip install transformers==4.15.0
> !pip install open_clip_torch
> !pip install clip-interrogator==0.5.0
> ```

Thank you very much. It is working for me. Before running Clip interrogator, running this code working fine.

**Comment by pharmapsychotic** [comment]
ah I heard about all the recent updates to Colab default libraries and Python version and this likely introduced the problem. thanks for hunting down fix!

**Comment by adventseo** [comment]
Thank You

**Comment by pharmapsychotic** [comment]
thanks for the fix @bradley-pearson6597 pinning the transformers version is now in the updated notebook
